### ISSUE TITLE
[💥] https://www.sony.jp/

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#20127]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:46:38.079Z] [Webhint Runner] Error runing job 6204e737-eaa1-4846-8d2b-35ab25e33681 - Part 5 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:46:43.021Z] [Webhint Runner] Error runing job 6204e737-eaa1-4846-8d2b-35ab25e33681 - Part 4 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"TypeError: Cannot read property 'includes' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at reportException (/app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at Timeout.callback [as _onTimeout] (/app/node_modules/jsdom/lib/jsdom/browser/Window.js:663:7)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:04.864Z] [Webhint Runner] Error runing job be178474-e1a4-437f-9949-b32b693cce05 - Part 4 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:05.519Z] [Webhint Runner] Error runing job be178474-e1a4-437f-9949-b32b693cce05 - Part 5 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:04.070Z] [Webhint Runner] Error runing job 6204e737-eaa1-4846-8d2b-35ab25e33681 - Part 2 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:06.799Z] [Webhint Runner] Error runing job 6204e737-eaa1-4846-8d2b-35ab25e33681 - Part 1 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:29.015Z] [Webhint Runner] Error runing job be178474-e1a4-437f-9949-b32b693cce05 - Part 1 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"TypeError: Cannot read property 'includes' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at reportException (/app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at Timeout.callback [as _onTimeout] (/app/node_modules/jsdom/lib/jsdom/browser/Window.js:663:7)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property 'nodeName' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
[2018-10-21T01:47:43.514Z] [Webhint Runner] Error runing job be178474-e1a4-437f-9949-b32b693cce05 - Part 2 of 5 TypeError: Cannot read property 'nodeName' of undefined
    at JSDOMConnector.traverseAndNotify (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:47:47)
    at Timeout.setTimeout [as _onTimeout] (/app/node_modules/@hint/connector-jsdom/dist/src/connector.js:156:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"www","host":"www","port":80},"hops":[],"resource":"http://www/","log":"     hostname: 'www',\n     host: 'www',\n     port: 80 },\n  hops: [],\n  resource: 'http://www/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
     hostname: 'www',
     host: 'www',
     port: 80 },
  hops: [],
  resource: 'http://www/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"www","host":"www","port":80},"hops":[],"resource":"http://www/","log":"     hostname: 'www',\n     host: 'www',\n     port: 80 },\n  hops: [],\n  resource: 'http://www/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
     hostname: 'www',
     host: 'www',
     port: 80 },
  hops: [],
  resource: 'http://www/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"www","host":"www","port":80},"hops":[],"resource":"http://www/","log":"     hostname: 'www',\n     host: 'www',\n     port: 80 },\n  hops: [],\n  resource: 'http://www/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
     hostname: 'www',
     host: 'www',
     port: 80 },
  hops: [],
  resource: 'http://www/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"www","host":"www","port":80},"hops":[],"resource":"http://www/","log":"     hostname: 'www',\n     host: 'www',\n     port: 80 },\n  hops: [],\n  resource: 'http://www/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
     hostname: 'www',
     host: 'www',
     port: 80 },
  hops: [],
  resource: 'http://www/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"www","host":"www","port":80},"hops":[],"resource":"http://www/","log":"     hostname: 'www',\n     host: 'www',\n     port: 80 },\n  hops: [],\n  resource: 'http://www/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
     hostname: 'www',
     host: 'www',
     port: 80 },
  hops: [],
  resource: 'http://www/' }
```
