### ISSUE TITLE
[💥] https://frontendmasters.com/

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#20417]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at HTMLFormElementImpl.submit (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:77:5)
    at HTMLFormElement.submit (/app/node_modules/jsdom/lib/jsdom/living/generated/HTMLFormElement.js:19:23)
    at HTMLFormElement.submit (https://www.googletagmanager.com/gtm.js?id=GTM-KNG43F:1944:316)
    at https://platform.twitter.com/widgets.js:8:28137
    at <anonymous>
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2018-11-14T00:47:37.606Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://px.ads.linkedin.com/collect/?time=1542156454574&pid=502908&url=https%3A%2F%2Ffrontendmasters.com%2F&pageUrl=https%3A%2F%2Ffrontendmasters.com%2F&ref=&fmt=js&s=1 fetched
2018-11-14T00:47:37.613Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load script: "https://widget.intercom.io/widget/w1ukcwje"
2018-11-14T00:47:38.005Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=1765c82e-cf8f-4153-8358-e1a53fc678ac&application=&x=b736a014-ccba-4504-8415-a569cf86ca9d& to be fetched
2018-11-14T00:47:38.006Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=1765c82e-cf8f-4153-8358-e1a53fc678ac&application=&x=b736a014-ccba-4504-8415-a569cf86ca9d&
2018-11-14T00:47:38.637Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=1765c82e-cf8f-4153-8358-e1a53fc678ac&application=&x=b736a014-ccba-4504-8415-a569cf86ca9d& fetched
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2018-11-14T00:48:04.774Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector next children
2018-11-14T00:48:04.775Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::div
2018-11-14T00:48:04.776Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://frontendmasters.com/favicon-32x32.png to be fetched
2018-11-14T00:48:04.776Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://frontendmasters.com/favicon-32x32.png
2018-11-14T00:48:04.926Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://frontendmasters.com/favicon-32x32.png fetched
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-01-14T19:57:01.601Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::div
2019-01-14T19:57:01.601Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector next children
2019-01-14T19:57:01.601Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::div
2019-01-14T19:57:01.602Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://frontendmasters.com/favicon-32x32.png to be fetched
2019-01-14T19:57:01.602Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://frontendmasters.com/favicon-32x32.png
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-01-14T19:56:35.280Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://syndication.twitter.com/i/jot?dnt=1&l=%7B%22widget_origin%22%3A%22https%3A%2F%2Ffrontendmasters.com%2F%22%2C%22widget_frame%22%3Afalse%2C%22widget_site_screen_name%22%3A%22frontendmasters%22%2C%22item_ids%22%3A%5B%221045040884742594560%22%5D%2C%22item_details%22%3A%7B%221045040884742594560%22%3A%7B%22item_type%22%3A0%7D%7D%2C%22unbucketed%22%3Atrue%2C%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1547495795252%2C%22dnt%22%3Atrue%2C%22client_version%22%3A%22d3704bd%3A1546534604449%22%2C%22format_version%22%3A%22d3704bd%3A1546534604449%22%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22element%22%3A%22notice%22%2C%22component%22%3A%22tweet%22%2C%22section%22%3A%22subject%22%2C%22action%22%3A%22seen%22%7D%7D&notice_seen=true
2019-01-14T19:56:35.318Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Not implemented: HTMLFormElement.prototype.submit
2019-01-14T19:56:35.346Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.facebook.com/tr/?id=1556952834559184&ev=Microdata&dl=https%3A%2F%2Ffrontendmasters.com%2F&rl=&if=false&ts=1547495794948&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%22og%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%2C%22og%3Atitle%22%3A%22Frontend%20Masters%20%E2%80%94%20Learn%20JavaScript%2C%20React%2C%20Vue%20%26%20Angular%20from%20Masters%20of%20Front-End%20Development!%22%2C%22og%3Aimage%22%3A%22https%3A%2F%2FFrontendMasters.com%2Fstatic-assets%2Fhome%2FFEM-OPENGraph.jpg%22%2C%22og%3Aurl%22%3A%22https%3A%2F%2FFrontendMasters.com%2F%22%2C%22og%3Asite_name%22%3A%22Frontend%20Masters%22%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.37&r=stable&ec=1&o=14&fbp=fb.1.1547495793602.2072280133&it=1547495793375&coo=false&es=automatic fetched
2019-01-14T19:56:35.389Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://syndication.twitter.com/i/jot?dnt=1&l=%7B%22widget_origin%22%3A%22https%3A%2F%2Ffrontendmasters.com%2F%22%2C%22widget_frame%22%3Afalse%2C%22widget_site_screen_name%22%3A%22frontendmasters%22%2C%22item_ids%22%3A%5B%221045040884742594560%22%5D%2C%22item_details%22%3A%7B%221045040884742594560%22%3A%7B%22item_type%22%3A0%7D%7D%2C%22unbucketed%22%3Atrue%2C%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1547495795252%2C%22dnt%22%3Atrue%2C%22client_version%22%3A%22d3704bd%3A1546534604449%22%2C%22format_version%22%3A%22d3704bd%3A1546534604449%22%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22element%22%3A%22notice%22%2C%22component%22%3A%22tweet%22%2C%22section%22%3A%22subject%22%2C%22action%22%3A%22seen%22%7D%7D&notice_seen=true fetched
2019-01-14T19:56:35.489Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=f56b2758-3578-4993-be4a-539804c72711&application=&x=93f0fcd6-a8c0-4a27-93f5-cc6edc713694& fetched
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-02-13T13:15:03.383Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://js.intercomcdn.com/frame.65fe7855.js fetched
2019-02-13T13:15:03.536Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://js.intercomcdn.com/vendor.8be05f97.js fetched
2019-02-13T13:15:04.385Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Redirect found for https://www.linkedin.com/px/li_sync?redirect=https%3A%2F%2Fpx.ads.linkedin.com%2Fcollect%2F%3Ftime%3D1550063703093%26pid%3D502908%26url%3Dhttps%253A%252F%252Ffrontendmasters.com%252F%26fmt%3Djs%26s%3D1%26cookiesTest%3Dtrue%26liSync%3Dtrue
2019-02-13T13:15:04.514Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://px.ads.linkedin.com/collect/?time=1550063703093&pid=502908&url=https%3A%2F%2Ffrontendmasters.com%2F&fmt=js&s=1 fetched
2019-02-13T13:15:04.518Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load script: "https://widget.intercom.io/widget/w1ukcwje"
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-02-22T06:22:17.064Z hint:app:node_modules:@hint:connector-jsdom:dist:src:evaluate-runner Error: Not implemented: HTMLFormElement.prototype.submit
    at module.exports (/app/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLFormElementImpl.submit (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:86:5)
    at HTMLFormElement.submit (/app/node_modules/jsdom/lib/jsdom/living/generated/HTMLFormElement.js:19:23)
    at https://platform.twitter.com/widgets.js:8:28096
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-02-22T06:22:13.959Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::div
2019-02-22T06:22:13.960Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://frontendmasters.com/favicon-32x32.png to be fetched
2019-02-22T06:22:13.972Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://frontendmasters.com/favicon-32x32.png
2019-02-22T06:22:18.057Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://frontendmasters.com/favicon-32x32.png fetched
2019-02-22T06:22:18.061Z hint:app:node_modules:@hint:hint-ssllabs:dist:src:hint Waiting for SSL Labs results for https://frontendmasters.com/
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"[object HTMLImageElement]"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-04-24T05:16:29.161Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.facebook.com/tr/?id=1556952834559184&ev=Microdata&dl=https%3A%2F%2Ffrontendmasters.com%2F&rl=&if=false&ts=1556082989158&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%22og%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%2C%22og%3Atitle%22%3A%22Frontend%20Masters%20%E2%80%94%20Learn%20JavaScript%2C%20React%2C%20Vue%20%26%20Angular%20from%20Masters%20of%20Front-End%20Development!%22%2C%22og%3Aimage%22%3A%22https%3A%2F%2Fstatic.frontendmasters.com%2Fassets%2Ffm%2Fmed%2Fhome%2FFEM-OPENGraph.jpg%22%2C%22og%3Aurl%22%3A%22https%3A%2F%2FFrontendMasters.com%2F%22%2C%22og%3Asite_name%22%3A%22Frontend%20Masters%22%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.47&r=stable&ec=1&o=14&fbp=fb.1.1556082988633.1832091934&it=1556082988295&coo=false&es=automatic&rqm=GET
2019-04-24T05:16:29.322Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.facebook.com/tr/?id=1556952834559184&ev=Microdata&dl=https%3A%2F%2Ffrontendmasters.com%2F&rl=&if=false&ts=1556082989158&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%22og%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%2C%22og%3Atitle%22%3A%22Frontend%20Masters%20%E2%80%94%20Learn%20JavaScript%2C%20React%2C%20Vue%20%26%20Angular%20from%20Masters%20of%20Front-End%20Development!%22%2C%22og%3Aimage%22%3A%22https%3A%2F%2Fstatic.frontendmasters.com%2Fassets%2Ffm%2Fmed%2Fhome%2FFEM-OPENGraph.jpg%22%2C%22og%3Aurl%22%3A%22https%3A%2F%2FFrontendMasters.com%2F%22%2C%22og%3Asite_name%22%3A%22Frontend%20Masters%22%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Advance%20your%20skills%20with%20in-depth%2C%20modern%20JavaScript%20and%20front-end%20engineering%20courses.%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.47&r=stable&ec=1&o=14&fbp=fb.1.1556082988633.1832091934&it=1556082988295&coo=false&es=automatic&rqm=GET fetched
2019-04-24T05:16:36.327Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=2ad6c9e1-9a09-4bfa-984d-194a160e2426&application=&x=b749e625-2b8f-48eb-b618-f3c42b3d21ae& to be fetched
2019-04-24T05:16:36.327Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=2ad6c9e1-9a09-4bfa-984d-194a160e2426&application=&x=b749e625-2b8f-48eb-b618-f3c42b3d21ae&
2019-04-24T05:16:36.645Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://usage.trackjs.com/usage.gif?token=477b9df4b9af41fea1d32431e1702aa5&correlationId=2ad6c9e1-9a09-4bfa-984d-194a160e2426&application=&x=b749e625-2b8f-48eb-b618-f3c42b3d21ae& fetched
```
