### ISSUE TITLE
[💥] https://www.emag.ro/

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#24194]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/app/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-01-28T17:19:57.331Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://secure.adnxs.com/seg?add=130915&redir=https%3A%2F%2Fsecure.adnxs.com%2Fgetuid%3Fhttps%3A%2F%2Fdis.criteo.com%2Fdis%2Frtb%2Fappnexus%2Fcookiematch.aspx%3Fappnxsid%3D%24UID fetched
2019-01-28T17:19:57.336Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://secure.adnxs.com/setuid?entity=52&code=244a4ce8-06d5-41ec-83ee-c8d5920b3976&seg=130915 to be fetched
2019-01-28T17:19:57.336Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://secure.adnxs.com/setuid?entity=52&code=244a4ce8-06d5-41ec-83ee-c8d5920b3976&seg=130915
2019-01-28T17:19:57.338Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load img: "https://simage2.pubmatic.com/AdServer/Pug?vcode=bz0yJnR5cGU9MSZqcz0xJmNvZGU9MzE3MiZ0bD00MzIwMA==&piggybackCookie=uid:244a4ce8-06d5-41ec-83ee-c8d5920b3976"
2019-01-28T17:19:57.379Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://secure.adnxs.com/setuid?entity=52&code=244a4ce8-06d5-41ec-83ee-c8d5920b3976&seg=130915 fetched
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-01-28T17:20:11.531Z hint:app:node_modules:@hint:connector-jsdom:dist:src:evaluate-runner Exception in queued GPT command
2019-01-28T17:20:11.624Z hint:app:node_modules:@hint:connector-jsdom:dist:src:evaluate-runner Exception in queued GPT command
(node:3061) UnhandledPromiseRejectionWarning: ReferenceError: MessageChannel is not defined
(node:3061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at onErrorWrapped (/app/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:41:19)
    at onLoadWrapped (/app/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:70:16)
    at Object.check (/app/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
    at Promise.resolve.then (/app/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:83:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-06-03T08:26:00.661Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load script: "https://www.gstatic.com/recaptcha/api2/v1558333958099/recaptcha__ro.js"
2019-06-03T08:26:00.663Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Uncaught [ReferenceError: recaptcha is not defined]
(node:4894) UnhandledPromiseRejectionWarning: ReferenceError: MessageChannel is not defined
(node:4894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Timeout"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-06-03T08:26:15.411Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.facebook.com/tr/?id=892293880821529&ev=Microdata&dl=https%3A%2F%2Fwww.emag.ro%2F&rl=&if=false&ts=1559550375409&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Cea%20mai%20variata%20gama%3A%20peste%202.000.000%20de%20produse%20IT%2C%20electronice%20si%20electrocasnice%2C%20gadgeturi%2C%20jucarii%2C%20imbracaminte%20si%20incaltaminte%20cu%20plata%20in%20rate.%20In%20plus%2C%20verifici%20coletul%20la%20livrare%20si%20ai%20retur%20gratuit%20in%2030%20de%20zile.%22%2C%22meta%3Akeywords%22%3A%22emag.ro%2C%20g%C4%83se%C8%99ti%2C%20mai%2C%20mult%2C%20dec%C3%A2t%2C%20crezi%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.47&r=stable&ec=1&o=14&it=1559550371878&coo=false&es=automatic&rqm=GET to be fetched
2019-06-03T08:26:15.416Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.facebook.com/tr/?id=892293880821529&ev=Microdata&dl=https%3A%2F%2Fwww.emag.ro%2F&rl=&if=false&ts=1559550375409&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Cea%20mai%20variata%20gama%3A%20peste%202.000.000%20de%20produse%20IT%2C%20electronice%20si%20electrocasnice%2C%20gadgeturi%2C%20jucarii%2C%20imbracaminte%20si%20incaltaminte%20cu%20plata%20in%20rate.%20In%20plus%2C%20verifici%20coletul%20la%20livrare%20si%20ai%20retur%20gratuit%20in%2030%20de%20zile.%22%2C%22meta%3Akeywords%22%3A%22emag.ro%2C%20g%C4%83se%C8%99ti%2C%20mai%2C%20mult%2C%20dec%C3%A2t%2C%20crezi%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.47&r=stable&ec=1&o=14&it=1559550371878&coo=false&es=automatic&rqm=GET
2019-06-03T08:26:15.460Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://secure.adnxs.com/setuid?entity=52&code=9eedbb91-0853-4da0-9593-c816e08f6584&seg=130915 fetched
2019-06-03T08:26:15.489Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load img: "https://secure.adnxs.com/setuid?entity=52&code=9eedbb91-0853-4da0-9593-c816e08f6584&seg=130915"
2019-06-03T08:26:15.606Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.facebook.com/tr/?id=892293880821529&ev=Microdata&dl=https%3A%2F%2Fwww.emag.ro%2F&rl=&if=false&ts=1559550375409&cd[Schema.org]=%5B%5D&cd[OpenGraph]=%7B%7D&cd[Meta]=%7B%22title%22%3A%22%22%2C%22meta%3Adescription%22%3A%22Cea%20mai%20variata%20gama%3A%20peste%202.000.000%20de%20produse%20IT%2C%20electronice%20si%20electrocasnice%2C%20gadgeturi%2C%20jucarii%2C%20imbracaminte%20si%20incaltaminte%20cu%20plata%20in%20rate.%20In%20plus%2C%20verifici%20coletul%20la%20livrare%20si%20ai%20retur%20gratuit%20in%2030%20de%20zile.%22%2C%22meta%3Akeywords%22%3A%22emag.ro%2C%20g%C4%83se%C8%99ti%2C%20mai%2C%20mult%2C%20dec%C3%A2t%2C%20crezi%22%7D&cd[DataLayer]=%5B%5D&cd[JSON-LD]=%5B%5D&sw=0&sh=0&v=2.8.47&r=stable&ec=1&o=14&it=1559550371878&coo=false&es=automatic&rqm=GET fetched
```
