### ISSUE TITLE
[💥] https://app.platin.training

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#27361]
## Error:

```bash
{"element":null,"error":{"code":"ESOCKETTIMEDOUT","connect":false},"hops":["https://app.platin.training/","https://app.platin.training/Dashboard"],"resource":"https://app.platin.training/","log":"    at ontimeout (timers.js:482:11) code: 'ESOCKETTIMEDOUT', connect: false },\n  hops: \n   [ 'https://app.platin.training/',\n     'https://app.platin.training/Dashboard' ],\n  resource: 'https://app.platin.training/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at ontimeout (timers.js:482:11) code: 'ESOCKETTIMEDOUT', connect: false },
  hops: 
   [ 'https://app.platin.training/',
     'https://app.platin.training/Dashboard' ],
  resource: 'https://app.platin.training/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ESOCKETTIMEDOUT","connect":false},"hops":["https://app.platin.training/","https://app.platin.training/Dashboard"],"resource":"https://app.platin.training/","log":"    at ontimeout (timers.js:482:11) code: 'ESOCKETTIMEDOUT', connect: false },\n  hops: \n   [ 'https://app.platin.training/',\n     'https://app.platin.training/Dashboard' ],\n  resource: 'https://app.platin.training/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at ontimeout (timers.js:482:11) code: 'ESOCKETTIMEDOUT', connect: false },
  hops: 
   [ 'https://app.platin.training/',
     'https://app.platin.training/Dashboard' ],
  resource: 'https://app.platin.training/' }
```
