### ISSUE TITLE
[💥] [undefined] http://<br> http://www.collegedrunkfest.com/sex.php?id=267

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#27707]
## Error:

```bash
"Invalid URL: http://<br> http://www.collegedrunkfest.com/sex.php?id=267"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  input: 'http://<br> http://www.collegedrunkfest.com/sex.php?id=267' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Invalid URL: http://<br> http://www.collegedrunkfest.com/sex.php?id=267"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": "summary",
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  input: 'http://<br> http://www.collegedrunkfest.com/sex.php?id=267' }
```
