### ISSUE TITLE
[💥] [undefined] http:// https://www.alibabacloud.com

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#32011]
## Error:

```bash
"Invalid URL: http:// https://www.alibabacloud.com"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at new URL (internal/url.js:332:5)
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) input: 'http:// https://www.alibabacloud.com' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Invalid URL: http:// https://www.alibabacloud.com"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at new URL (internal/url.js:332:5)
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) input: 'http:// https://www.alibabacloud.com' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Invalid URL: http:// https://www.alibabacloud.com"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at new URL (internal/url.js:332:5)
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) input: 'http:// https://www.alibabacloud.com' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Invalid URL: http:// https://www.alibabacloud.com"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "https-only": "error",
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at new URL (internal/url.js:332:5)
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) input: 'http:// https://www.alibabacloud.com' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Invalid URL: http:// https://www.alibabacloud.com"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
    at new URL (internal/url.js:332:5)
    at process.run (/app/dist/src/lib/microservices/worker-service/webhint-runner.js:66:50)
    at process.emit (events.js:189:13)
    at emit (internal/child_process.js:820:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) input: 'http:// https://www.alibabacloud.com' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property '_dispatch' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-03-29T23:36:22.839Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Error: Could not load img: "https://arms-retcode-sg.aliyuncs.com/r.png?t=perf&times=1&page=us.alibabacloud.com&tag=&begin=1553902579046&ct=&bandwidth=-1&navtype=Other&fmp=1221&sr=0x0&vp=1024x768&uid=Ijj4qtICumjpb0h6k1m2dabut5dy&pid=gwqva717a7%4078a7818c153e058&_v=1.5.1&sid=snj1httLu2vpvqhC81L5dOkez1p1&sampling=1&z=jtuph1df"
2019-03-29T23:36:22.978Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.google.com/pagead/1p-user-list/946920104/?random=1553902579495&cv=9&fst=1553900400000&num=1&bg=ffffff&guid=ON&eid=376635470&u_h=0&u_w=0&u_ah=0&u_aw=0&u_cd=24&u_his=1&u_tz=0&u_java=false&u_nplug=0&u_nmime=0&gtm=2oa3i1&data=event%3Dgtag.config&frm=0&url=https%3A%2F%2Fus.alibabacloud.com%2F&tiba=Empower%20Your%20Business%20in%20USA%20%26%20Canada%20with%20Alibaba%20Cloud%27s%20Cloud%20Products%20%26%20Services&async=1&fmt=3&cdct=2&is_vtc=1&random=2091866891&resp=GooglemKTybQhCsO&rmt_tld=0&ipr=y to be fetched
2019-03-29T23:36:22.979Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.google.com/pagead/1p-user-list/946920104/?random=1553902579495&cv=9&fst=1553900400000&num=1&bg=ffffff&guid=ON&eid=376635470&u_h=0&u_w=0&u_ah=0&u_aw=0&u_cd=24&u_his=1&u_tz=0&u_java=false&u_nplug=0&u_nmime=0&gtm=2oa3i1&data=event%3Dgtag.config&frm=0&url=https%3A%2F%2Fus.alibabacloud.com%2F&tiba=Empower%20Your%20Business%20in%20USA%20%26%20Canada%20with%20Alibaba%20Cloud%27s%20Cloud%20Products%20%26%20Services&async=1&fmt=3&cdct=2&is_vtc=1&random=2091866891&resp=GooglemKTybQhCsO&rmt_tld=0&ipr=y
2019-03-29T23:36:23.008Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.google.com/pagead/1p-user-list/946920104/?random=1553902579512&cv=9&fst=1553900400000&num=1&bg=ffffff&guid=ON&eid=376635470&u_h=0&u_w=0&u_ah=0&u_aw=0&u_cd=24&u_his=1&u_tz=0&u_java=false&u_nplug=0&u_nmime=0&gtm=2oa3i1&data=event%3Dgtag.config&frm=0&url=https%3A%2F%2Fus.alibabacloud.com%2F&tiba=Empower%20Your%20Business%20in%20USA%20%26%20Canada%20with%20Alibaba%20Cloud%27s%20Cloud%20Products%20%26%20Services&async=1&fmt=3&cdct=2&is_vtc=1&random=2684022966&resp=GooglemKTybQhCsO&rmt_tld=0&ipr=y to be fetched
2019-03-29T23:36:23.008Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.google.com/pagead/1p-user-list/946920104/?random=1553902579512&cv=9&fst=1553900400000&num=1&bg=ffffff&guid=ON&eid=376635470&u_h=0&u_w=0&u_ah=0&u_aw=0&u_cd=24&u_his=1&u_tz=0&u_java=false&u_nplug=0&u_nmime=0&gtm=2oa3i1&data=event%3Dgtag.config&frm=0&url=https%3A%2F%2Fus.alibabacloud.com%2F&tiba=Empower%20Your%20Business%20in%20USA%20%26%20Canada%20with%20Alibaba%20Cloud%27s%20Cloud%20Products%20%26%20Services&async=1&fmt=3&cdct=2&is_vtc=1&random=2684022966&resp=GooglemKTybQhCsO&rmt_tld=0&ipr=y
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property '_dispatch' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-03-29T23:36:28.584Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Facebook Pixel Error: Duplicate Pixel ID: 260480767702896
2019-03-29T23:36:28.585Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.facebook.com/tr/?id=260480767702896&ev=PageView&dl=https%3A%2F%2Fhk.alibabacloud.com%2F&rl=&if=false&ts=1553902588582&v=2.5.1
2019-03-29T23:36:28.635Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://fourier.alibaba.com/ts?url=&token=BDEx7QJ0yV4UvmVKKAr3isGbSrzLHqWQf4fJ5RNGLfgXOlGMW261YN9MWlRc6T3I&cna=9pklFTRH%2FiMCAQ1ArlbpLtsy&ext=1 to be fetched
2019-03-29T23:36:28.636Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://fourier.alibaba.com/ts?url=&token=BDEx7QJ0yV4UvmVKKAr3isGbSrzLHqWQf4fJ5RNGLfgXOlGMW261YN9MWlRc6T3I&cna=9pklFTRH%2FiMCAQ1ArlbpLtsy&ext=1
2019-03-29T23:36:28.685Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://arms-retcode-sg.aliyuncs.com/r.png?t=pv&times=1&page=hk.alibabacloud.com&tag=&begin=1553902586669&uid=42jtatI9uUhpswhsm9RpgpFrt1w5&dt=%E9%98%BF%E9%87%8C%E9%9B%B2%E6%8F%90%E4%BE%9B%E5%85%A8%E5%A5%97%E9%9B%B2%E8%A8%88%E7%AE%97%E6%9C%8D%E5%8B%99%E5%8F%8A%E8%A7%A3%E6%B1%BA%E6%96%B9%E6%A1%88%E7%82%BA%E9%A6%99%E6%B8%AF%E4%BC%81%E6%A5%AD%E7%9A%84%E6%95%B8%E5%AD%97%E5%8C%96%E8%BD%89%E5%9E%8B%E5%8A%A9%E5%8A%9B&dl=https%3A%2F%2Fhk.alibabacloud.com%2F&dr=&dpr=1.00&de=utf-8&ul=tc&sr=0x0&vp=1024x768&ct=&pid=gwqva717a7%4078a7818c153e058&_v=1.5.1&sid=X6jnbts2ut6pb4h7090jgt7iqOn6&sampling=1&z=jtuph9gh fetched
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property '_dispatch' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-03-29T23:36:32.868Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://www.facebook.com/tr/?id=260480767702896&ev=PageView&dl=https%3A%2F%2Fsg.alibabacloud.com%2F&rl=&if=false&ts=1553902592867&v=2.5.1 to be fetched
2019-03-29T23:36:32.869Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector Console: Facebook Pixel Error: Duplicate Pixel ID: 260480767702896
2019-03-29T23:36:32.869Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://www.facebook.com/tr/?id=260480767702896&ev=PageView&dl=https%3A%2F%2Fsg.alibabacloud.com%2F&rl=&if=false&ts=1553902592867&v=2.5.1
2019-03-29T23:36:32.889Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://fourier.alibaba.com/ts?url=&token=BJCQTtXd-I3qLaSJllHWN3Nua9_iWXSjpihI5ophXOu-xTBvMmlEM-bjmxclDix7&cna=%2FJklFS8bqnMCAQ1Arlao7OdP&ext=1 to be fetched
2019-03-29T23:36:32.890Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://fourier.alibaba.com/ts?url=&token=BJCQTtXd-I3qLaSJllHWN3Nua9_iWXSjpihI5ophXOu-xTBvMmlEM-bjmxclDix7&cna=%2FJklFS8bqnMCAQ1Arlao7OdP&ext=1
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Cannot read property '_dispatch' of undefined"
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "https-only": "error",
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-03-29T23:37:05.156Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::span
2019-03-29T23:37:05.156Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector next children
2019-03-29T23:37:05.156Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::li
2019-03-29T23:37:05.156Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector next children
2019-03-29T23:37:05.156Z hint:app:node_modules:@hint:connector-jsdom:dist:src:connector emitting element::a
```
