### ISSUE TITLE
[💥] [undefined] http://ameli.fr

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#33532]
## Error:

```bash
{"element":null,"error":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"hops":["http://ameli.fr/"],"resource":"http://ameli.fr/","log":"  error:\n   { Error: read ECONNRESET\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },\n  hops: [ 'http://ameli.fr/' ],\n  resource: 'http://ameli.fr/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
  error:
   { Error: read ECONNRESET
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  hops: [ 'http://ameli.fr/' ],
  resource: 'http://ameli.fr/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"hops":["http://ameli.fr/"],"resource":"http://ameli.fr/","log":"  error:\n   { Error: read ECONNRESET\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },\n  hops: [ 'http://ameli.fr/' ],\n  resource: 'http://ameli.fr/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
  error:
   { Error: read ECONNRESET
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  hops: [ 'http://ameli.fr/' ],
  resource: 'http://ameli.fr/' }
```
