### ISSUE TITLE
[💥] [undefined] https://www.mycinema.pro

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#34795]
## Error:

```bash
{"element":null,"error":{"bytesParsed":0,"code":"HPE_HEADER_OVERFLOW"},"hops":[],"resource":"https://www.mycinema.pro/","log":"       at readableAddChunk (_stream_readable.js:265:11)\n       at TLSSocket.Readable.push (_stream_readable.js:220:10)\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_HEADER_OVERFLOW' },\n  hops: [],\n  resource: 'https://www.mycinema.pro/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
       at readableAddChunk (_stream_readable.js:265:11)
       at TLSSocket.Readable.push (_stream_readable.js:220:10)
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_HEADER_OVERFLOW' },
  hops: [],
  resource: 'https://www.mycinema.pro/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"bytesParsed":0,"code":"HPE_HEADER_OVERFLOW"},"hops":[],"resource":"https://www.mycinema.pro/","log":"       at readableAddChunk (_stream_readable.js:265:11)\n       at TLSSocket.Readable.push (_stream_readable.js:220:10)\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_HEADER_OVERFLOW' },\n  hops: [],\n  resource: 'https://www.mycinema.pro/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
       at readableAddChunk (_stream_readable.js:265:11)
       at TLSSocket.Readable.push (_stream_readable.js:220:10)
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17) bytesParsed: 0, code: 'HPE_HEADER_OVERFLOW' },
  hops: [],
  resource: 'https://www.mycinema.pro/' }
```
