### ISSUE TITLE
[💥] [undefined] http://www.singularitybd.com

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#35739]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-10T00:51:27.106Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-10T00:51:27.113Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-10T00:51:27.114Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-10T00:51:27.115Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-10T00:51:27.121Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-10T00:51:28.945Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-10T00:51:28.948Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-10T00:51:28.949Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-10T00:51:28.952Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-10T00:51:28.956Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-10T00:51:26.377Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-10T00:51:26.377Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-10T00:51:26.378Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-10T00:51:26.380Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-10T00:51:26.384Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "https-only": "error",
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-10T00:51:30.618Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-10T00:51:30.619Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-10T00:51:30.619Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-10T00:51:30.621Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-10T00:51:30.625Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ETIMEDOUT","connect":true},"hops":[],"resource":"http://www.singularitybd.com/","log":"       at tryOnTimeout (timers.js:300:5)\n       at listOnTimeout (timers.js:263:5)\n       at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: true },\n  hops: [],\n  resource: 'http://www.singularitybd.com/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: true },
  hops: [],
  resource: 'http://www.singularitybd.com/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:01:15.298Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:01:15.299Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:01:15.299Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:01:15.301Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:01:15.302Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:01:15.756Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:01:15.757Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:01:15.757Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:01:15.759Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:01:15.760Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:01:16.222Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:01:16.223Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:01:16.223Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:01:16.225Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:01:16.226Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"code":"ETIMEDOUT","connect":true},"hops":[],"resource":"http://www.singularitybd.com/","log":"       at tryOnTimeout (timers.js:300:5)\n       at listOnTimeout (timers.js:263:5)\n       at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: true },\n  hops: [],\n  resource: 'http://www.singularitybd.com/' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
       at tryOnTimeout (timers.js:300:5)
       at listOnTimeout (timers.js:263:5)
       at Timer.processTimers (timers.js:223:10) code: 'ETIMEDOUT', connect: true },
  hops: [],
  resource: 'http://www.singularitybd.com/' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "https-only": "error",
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:01:17.771Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:01:17.772Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:01:17.772Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:01:17.774Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:01:17.775Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:07:26.600Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:07:26.601Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:07:26.602Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:07:26.603Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:07:26.604Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "apple-touch-icons": "warning",
            "content-type": "error",
            "disown-opener": "error",
            "highest-available-document-mode": "error",
            "http-cache": "error",
            "http-compression": [
                "error",
                {
                    "html": {
                        "zopfli": false,
                        "brotli": false
                    }
                }
            ],
            "https-only": "error",
            "manifest-app-name": "warning",
            "manifest-exists": "off",
            "manifest-file-extension": "warning",
            "manifest-is-valid": "error",
            "meta-charset-utf-8": "error",
            "meta-viewport": "error",
            "minified-js": "error",
            "no-bom": "error",
            "no-broken-links": "off",
            "no-disallowed-headers": [
                "error",
                {
                    "ignore": [
                        "Server"
                    ]
                }
            ],
            "no-friendly-error-pages": "warning",
            "no-html-only-headers": "error",
            "no-http-redirects": [
                "error",
                {
                    "max-target-redirects": 1
                }
            ],
            "no-p3p": "off",
            "no-protocol-relative-urls": "error",
            "performance-budget": [
                "error",
                {
                    "connectionType": "4G",
                    "loadTime": 5
                }
            ],
            "sri": "error",
            "strict-transport-security": "error",
            "validate-set-cookie-header": "error",
            "x-content-type-options": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:07:28.860Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:07:28.860Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:07:28.861Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:07:28.862Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:07:28.863Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "html-checker": "off",
            "image-optimization-cloudinary": [
                "error",
                {
                    "threshold": 5
                }
            ],
            "no-vulnerable-javascript-libraries": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:07:27.049Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:07:27.050Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:07:27.050Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:07:27.051Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:07:27.053Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 120000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "axe": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 5000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:07:37.355Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:07:37.356Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:07:37.356Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:07:37.358Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:07:37.359Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
"Error: The Google Maps JavaScript API does not support this browser."
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
2019-05-13T17:07:37.222Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js to be fetched
2019-05-13T17:07:37.223Z hint:app:node_modules:@hint:connector-jsdom:dist:src:resource-loader resource https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js to be fetched
2019-05-13T17:07:37.223Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/common.js
2019-05-13T17:07:37.227Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/util.js
2019-05-13T17:07:37.229Z hint:app:node_modules:@hint:utils-connector-tools:dist:src:requester Requesting https://maps.googleapis.com/maps-api-v3/api/js/36/12/controls.js
```
