### ISSUE TITLE
[💥] [undefined] https://beta.nov.com/success-stories/real-performance-for-real-world-rigs

### ISSUE THREAD

**Issue by NellieTheNarwhal** [webhintio/scan-issues#39391]
## Error:

```bash
{"element":null,"error":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"hops":[],"resource":"https://beta.nov.com/success-stories/real-performance-for-real-world-rigs","log":"   { Error: read ECONNRESET\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },\n  hops: [],\n  resource:\n   'https://beta.nov.com/success-stories/real-performance-for-real-world-rigs' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "stylesheet-limits": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
   { Error: read ECONNRESET
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  hops: [],
  resource:
   'https://beta.nov.com/success-stories/real-performance-for-real-world-rigs' }
```

**Comment by NellieTheNarwhal** [comment]
## Error:

```bash
{"element":null,"error":{"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"},"hops":[],"resource":"https://beta.nov.com/success-stories/real-performance-for-real-world-rigs","log":"   { Error: read ECONNRESET\n       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },\n  hops: [],\n  resource:\n   'https://beta.nov.com/success-stories/real-performance-for-real-world-rigs' }"}
```

## Configuration:

```json
[
    {
        "hintsTimeout": 170000,
        "parsers": [
            "manifest"
        ],
        "hints": {
            "ssllabs": "error"
        },
        "formatters": [
            "summary"
        ],
        "connector": {
            "options": {
                "waitFor": 1000
            },
            "name": "jsdom"
        },
        "browserslist": [
            "> 1%",
            "last 1 version"
        ],
        "ignoredUrls": [
            {
                "domain": "^https?://cdn\\.jsdelivr\\.net/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://.*\\.google-analytics\\.com/.*",
                "hints": [
                    "*"
                ]
            },
            {
                "domain": "^https?://fonts\\.googleapis\\.com/.*",
                "hints": [
                    "*"
                ]
            }
        ]
    }
]
```

## Log:

```json
   { Error: read ECONNRESET
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' },
  hops: [],
  resource:
   'https://beta.nov.com/success-stories/real-performance-for-real-world-rigs' }
```
